// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADKuY3-x5ArM6gIDOvsw97uGuVOWTYBi0',
    appId: '1:415248150968:web:8e29d52f8e2cf34658df4d',
    messagingSenderId: '415248150968',
    projectId: 'insta-clone-ed009',
    authDomain: 'insta-clone-ed009.firebaseapp.com',
    storageBucket: 'insta-clone-ed009.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKwFZ52B5tcKNDaTrh-2S4lyyemkpSeI',
    appId: '1:415248150968:android:8f8c42b96720c34c58df4d',
    messagingSenderId: '415248150968',
    projectId: 'insta-clone-ed009',
    storageBucket: 'insta-clone-ed009.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADKuY3-x5ArM6gIDOvsw97uGuVOWTYBi0',
    appId: '1:415248150968:web:e74287d8c9e14e5b58df4d',
    messagingSenderId: '415248150968',
    projectId: 'insta-clone-ed009',
    authDomain: 'insta-clone-ed009.firebaseapp.com',
    storageBucket: 'insta-clone-ed009.firebasestorage.app',
  );
}
